### ISSUE TITLE
Bug with search

### ISSUE THREAD

**Issue by joseBarreto** [raphaelcunha/browser-code#1]
Hi Raphael,
 when I clicked in search and open a repository, when clicking in "Go back" not save my last search.
## [Search]

![1](https://cloud.githubusercontent.com/assets/11754960/14528932/708086d0-0228-11e6-95c1-1e6991a8ffe5.PNG)
## [Open repository]

![2](https://cloud.githubusercontent.com/assets/11754960/14528933/7080dba8-0228-11e6-92b9-2f46e02b7892.PNG)
## [Go back]

![3](https://cloud.githubusercontent.com/assets/11754960/14528931/707c36fc-0228-11e6-92c8-05a1925e825f.PNG)

**Comment by raphaelcunha** [comment]
Ok, now resource is correcly
